---
# file: roles/common/tasks/main.yml


# Setup users
- user: name=django uid=1040 shell=/bin/bash
  sudo: yes

- user: name=sean uid=1041 group=admin shell=/bin/bash
  sudo: yes

# Install packages 
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  tags: apt
  sudo: yes

- name: ensure elasticsearch apt key exists
  apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch
  sudo: yes

- name: ensure elasticsearch repo is there
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/0.90/debian stable main'
  sudo: yes

- name: ensure java repo is there
  apt_repository: repo='ppa:webupd8team/java'
  sudo: yes

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  sudo: yes

- name: install stuff essentials
  apt: name={{item}} state=installed update_cache=true 
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - htop
    - curl
    - openssh-server
    - memcached
    - vim
    - elasticsearch
    - oracle-java7-installer
    - git
    - mercurial

- name: Enable Elasticsearch on start
  service: name=elasticsearch enabled=yes
  sudo: yes

- pip: name=virtualenv
  sudo: yes
